name: Build/release

on:
  workflow_dispatch:

jobs:
  release:
    name: Build/release
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Clean install
        run: npm install

      - name: Build/release Electron app
        env:
          GIT_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm run publish
