name: Build/release

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  release:
    name: Build/release
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        package-manager: [npm]
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: ${{ matrix.package-manager }} install

      - name: Build/release Electron app
        uses: electron-forge/bundle-action
